using System.Text.Json.Serialization;
using PartyGame.Contracts.Serialization;

namespace PartyGame.Contracts;

/// <summary>
/// Identifies a game. Snapshots carry it so that a client can tell a new game, whose versions start over,
/// from an older snapshot of the game it shows.
/// </summary>
/// <param name="Value">The underlying identifier, generated by the server.</param>
[JsonConverter(typeof(TypedIdJsonConverterFactory))]
public readonly record struct GameId(Guid Value);
