using System.Text.Json.Serialization;
using PartyGame.Contracts.Serialization;

namespace PartyGame.Contracts;

/// <summary>
/// Identifies a player for the whole game, independently of their SignalR connections.
/// </summary>
/// <param name="Value">The underlying identifier, generated by the server.</param>
[JsonConverter(typeof(TypedIdJsonConverterFactory))]
public readonly record struct PlayerId(Guid Value);
