using System.Text.Json.Serialization;
using PartyGame.Contracts.Serialization;

namespace PartyGame.Contracts;

/// <summary>
/// Identifies one round played during a game. Intents and timers of a round carry it, so that one aimed at a round that
/// is over is told from one aimed at the current round.
/// </summary>
/// <param name="Value">The underlying identifier, generated by the server when the round starts.</param>
[JsonConverter(typeof(TypedIdJsonConverterFactory))]
public readonly record struct RoundId(Guid Value);
