<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PartyGame.Contracts\PartyGame.Contracts.csproj" />
    <ProjectReference Include="..\PartyGame.Engine\PartyGame.Engine.csproj" />
    <ProjectReference Include="..\PartyGame.Content\PartyGame.Content.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PartyGame.Server.Tests" />
  </ItemGroup>

</Project>
