// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { BuzzerButtonState } from './BuzzerButtonState';

export interface BlindTestPlayerView {
    readonly type: 'blindtest';
    readonly trackNumber: number;
    readonly trackCount: number;
    readonly opening: number;
    readonly opensAt: number | null;
    readonly buzzer: BuzzerButtonState;
    readonly winner: string | null;
    readonly foundTitle: boolean;
    readonly foundArtist: boolean;
}
