// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { RoundId } from './RoundId';

export interface BlindTestBuzz {
    readonly type: 'blindtest.buzz';
    readonly roundId: RoundId;
    readonly trackNumber: number;
    readonly opening: number;
    readonly pressedAt: number;
}
