// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { BuzzerQuestionPhase } from './BuzzerQuestionPhase';

export interface BuzzerDisplayView {
    readonly type: 'buzzer';
    readonly questionNumber: number;
    readonly questionCount: number;
    readonly phase: BuzzerQuestionPhase;
    readonly text: string | null;
    readonly imageUrl: string | null;
    readonly winner: string | null;
}
