// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { ClientErrorKind } from './ClientErrorKind';
import type { Role } from './Role';

export interface ClientErrorReport {
    readonly role: Role;
    readonly page: string;
    readonly kind: ClientErrorKind;
    readonly message: string;
    readonly stack: string | null;
    readonly roundViewType: string | null;
    readonly snapshotVersion: number | null;
    readonly buildId: string | null;
}
