// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { ConnectionTransport } from './ConnectionTransport';
import type { PlayerId } from './PlayerId';

export interface ConnectionQuality {
    readonly playerId: PlayerId | null;
    readonly transport: ConnectionTransport;
    readonly roundTrip: number | null;
    readonly reconnections: number;
}
