// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { DisplayPlayer } from './DisplayPlayer';
import type { GameId } from './GameId';
import type { Phase } from './Phase';

export interface DisplaySnapshot {
    readonly gameId: GameId;
    readonly version: number;
    readonly phase: Phase;
    readonly joinAddress: string | null;
    readonly players: readonly DisplayPlayer[];
}
