// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { BlindTestDisplayView } from './BlindTestDisplayView';
import type { BuzzerDisplayView } from './BuzzerDisplayView';
import type { QuizDisplayView } from './QuizDisplayView';

export type DisplayRoundView = BlindTestDisplayView | BuzzerDisplayView | QuizDisplayView;
