// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { BlindTestJudge } from './BlindTestJudge';
import type { BlindTestNextTrack } from './BlindTestNextTrack';
import type { BlindTestPlay } from './BlindTestPlay';
import type { BlindTestRevealAnswer } from './BlindTestRevealAnswer';
import type { BlindTestSkipTrack } from './BlindTestSkipTrack';
import type { BuzzerAskQuestion } from './BuzzerAskQuestion';
import type { BuzzerJudge } from './BuzzerJudge';
import type { BuzzerNextQuestion } from './BuzzerNextQuestion';
import type { BuzzerRevealAnswer } from './BuzzerRevealAnswer';
import type { BuzzerShowQuestion } from './BuzzerShowQuestion';
import type { QuizNextQuestion } from './QuizNextQuestion';
import type { QuizRevealAnswer } from './QuizRevealAnswer';
import type { QuizShowChoice } from './QuizShowChoice';
import type { QuizShowQuestion } from './QuizShowQuestion';
import type { QuizSkipQuestion } from './QuizSkipQuestion';

export type GameMasterRoundIntent = BlindTestJudge | BlindTestNextTrack | BlindTestPlay | BlindTestRevealAnswer | BlindTestSkipTrack | BuzzerAskQuestion | BuzzerJudge | BuzzerNextQuestion | BuzzerRevealAnswer | BuzzerShowQuestion | QuizNextQuestion | QuizRevealAnswer | QuizShowChoice | QuizShowQuestion | QuizSkipQuestion;
