// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { QuizLockAnswers } from './QuizLockAnswers';
import type { QuizOpenAnswers } from './QuizOpenAnswers';

export type GameMasterRoundIntent = QuizLockAnswers | QuizOpenAnswers;
