// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { BuzzerAskQuestion } from './BuzzerAskQuestion';
import type { QuizNextQuestion } from './QuizNextQuestion';
import type { QuizRevealAnswer } from './QuizRevealAnswer';
import type { QuizShowChoice } from './QuizShowChoice';
import type { QuizShowQuestion } from './QuizShowQuestion';
import type { QuizSkipQuestion } from './QuizSkipQuestion';

export type GameMasterRoundIntent = BuzzerAskQuestion | QuizNextQuestion | QuizRevealAnswer | QuizShowChoice | QuizShowQuestion | QuizSkipQuestion;
