// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { GameId } from './GameId';
import type { GameMasterJoinAddress } from './GameMasterJoinAddress';
import type { GameMasterPackCatalog } from './GameMasterPackCatalog';
import type { GameMasterPlayer } from './GameMasterPlayer';
import type { GameMasterRoundView } from './GameMasterRoundView';
import type { GameMasterSavedGame } from './GameMasterSavedGame';
import type { Phase } from './Phase';
import type { RankedPlayer } from './RankedPlayer';
import type { RoundInfo } from './RoundInfo';

export interface GameMasterSnapshot {
    readonly gameId: GameId;
    readonly version: number;
    readonly phase: Phase;
    readonly players: readonly GameMasterPlayer[];
    readonly minimumPlayerCount: number;
    readonly joinAddress: string | null;
    readonly joinAddressCandidates: readonly GameMasterJoinAddress[];
    readonly packCatalog: GameMasterPackCatalog | null;
    readonly selectedPackId: string | null;
    readonly packTitle: string | null;
    readonly round: RoundInfo | null;
    readonly roundView: GameMasterRoundView | null;
    readonly ranking: readonly RankedPlayer[];
    readonly nextRoundTitle: string | null;
    readonly roundSkipped: boolean;
    readonly savedGame: GameMasterSavedGame | null;
    readonly joinCodeShown: boolean;
}
