// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { GameMasterPack } from './GameMasterPack';

export interface GameMasterPackCatalog {
    readonly directory: string;
    readonly packs: readonly GameMasterPack[];
}
