// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { BlindTestGameMasterView } from './BlindTestGameMasterView';
import type { BuzzerGameMasterView } from './BuzzerGameMasterView';
import type { OpenQuestionGameMasterView } from './OpenQuestionGameMasterView';
import type { QuizGameMasterView } from './QuizGameMasterView';

export type GameMasterRoundView = BlindTestGameMasterView | BuzzerGameMasterView | OpenQuestionGameMasterView | QuizGameMasterView;
