// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { RoundInfo } from './RoundInfo';
import type { RoundStep } from './RoundStep';

export interface GameMasterPreview {
    readonly packId: string;
    readonly round: RoundInfo;
    readonly step: RoundStep;
    readonly hasExcerpt: boolean;
}
