// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { GameId } from './GameId';
import type { Phase } from './Phase';
import type { RoundInfo } from './RoundInfo';
import type { RoundStep } from './RoundStep';

export interface GameMasterSavedGame {
    readonly gameId: GameId;
    readonly savedAt: number;
    readonly phase: Phase;
    readonly packTitle: string | null;
    readonly round: RoundInfo | null;
    readonly step: RoundStep | null;
    readonly playerCount: number;
    readonly missingMedia: readonly string[];
}
