// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { GameId } from './GameId';
import type { Phase } from './Phase';

export interface GameMasterSnapshot {
    readonly gameId: GameId;
    readonly version: number;
    readonly phase: Phase;
    readonly playerCount: number;
}
