// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { GameMasterPackRound } from './GameMasterPackRound';
import type { PackProblem } from './PackProblem';

export interface GameMasterPack {
    readonly id: string;
    readonly title: string | null;
    readonly roundCount: number | null;
    readonly isValid: boolean;
    readonly rounds: readonly GameMasterPackRound[];
    readonly problems: readonly PackProblem[];
}
