// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { ScheduledRoundStatus } from './ScheduledRoundStatus';

export interface GameMasterScheduledRound {
    readonly roundIndex: number;
    readonly title: string;
    readonly mode: string;
    readonly status: ScheduledRoundStatus;
}
