// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { DisplaySnapshot } from './DisplaySnapshot';
import type { GameMasterSnapshot } from './GameMasterSnapshot';
import type { IncidentList } from './IncidentList';
import type { NetworkHealth } from './NetworkHealth';
import type { PlayerSnapshot } from './PlayerSnapshot';
import type { Welcome } from './Welcome';

export interface IGameClient {
    ReceiveWelcome(welcome: Welcome): void;
    ReceiveDisplaySnapshot(snapshot: DisplaySnapshot): void;
    ReceiveGameMasterSnapshot(snapshot: GameMasterSnapshot): void;
    ReceivePlayerSnapshot(snapshot: PlayerSnapshot): void;
    ReceiveIncidents(incidents: IncidentList): void;
    ReceiveNetworkHealth(health: NetworkHealth): void;
}
