// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { IncidentCode } from './IncidentCode';
import type { Role } from './Role';
import type { RoundInfo } from './RoundInfo';

export interface Incident {
    readonly id: number;
    readonly code: IncidentCode;
    readonly round: RoundInfo | null;
    readonly role: Role | null;
    readonly count: number;
    readonly lastOccurredAt: number;
}
