// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

export type * from './Announcement';
export type * from './AnnouncementRefusal';
export type * from './AnnouncementResult';
export type * from './ChooseAdvertisedAddressRefusal';
export type * from './ChooseAdvertisedAddressRequest';
export type * from './ChooseAdvertisedAddressResult';
export type * from './ClockSyncResult';
export type * from './DisplayPlayer';
export type * from './DisplayRoundView';
export type * from './DisplaySnapshot';
export type * from './GameId';
export type * from './GameMasterJoinAddress';
export type * from './GameMasterPlayer';
export type * from './GameMasterRoundIntent';
export type * from './GameMasterRoundView';
export type * from './GameMasterSnapshot';
export type * from './IGameClient';
export type * from './JoinRefusal';
export type * from './JoinRequest';
export type * from './JoinResult';
export type * from './NextRoundRequest';
export type * from './PackProblem';
export type * from './PackProblemCode';
export type * from './Phase';
export type * from './PlayerId';
export type * from './PlayerRoundIntent';
export type * from './PlayerRoundView';
export type * from './PlayerSnapshot';
export type * from './QuizDisplayView';
export type * from './QuizGameMasterIntent';
export type * from './QuizGameMasterView';
export type * from './QuizPlayerIntent';
export type * from './QuizPlayerView';
export type * from './RenamePlayerRefusal';
export type * from './RenamePlayerRequest';
export type * from './RenamePlayerResult';
export type * from './ResumeSessionRefusal';
export type * from './ResumeSessionRequest';
export type * from './ResumeSessionResult';
export type * from './Role';
export type * from './RoundId';
export type * from './RoundInfo';
export type * from './StaleBuildReport';
export type * from './StartGameRefusal';
export type * from './StartGameResult';
export type * from './Welcome';
