// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { JoinRefusal } from './JoinRefusal';
import type { PlayerId } from './PlayerId';

export interface JoinResult {
    readonly refusal: JoinRefusal | null;
    readonly playerId: PlayerId | null;
    readonly token: string | null;
}
