// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { ConnectionTransport } from './ConnectionTransport';

export interface NetworkCheckResult {
    readonly transport: ConnectionTransport;
    readonly sameSubnet: boolean | null;
}
