// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { ConnectionQuality } from './ConnectionQuality';
import type { NetworkDiagnostic } from './NetworkDiagnostic';

export interface NetworkHealth {
    readonly diagnostics: readonly NetworkDiagnostic[];
    readonly connections: readonly ConnectionQuality[];
}
