// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { DeviceKind } from './DeviceKind';
import type { DiagnosticVerdict } from './DiagnosticVerdict';

export interface NetworkDiagnostic {
    readonly device: DeviceKind;
    readonly reportedAt: number;
    readonly verdict: DiagnosticVerdict;
    readonly roundTripMedian: number | null;
}
