// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { PlayerId } from './PlayerId';
import type { RoundId } from './RoundId';

export interface OpenQuestionJudge {
    readonly type: 'openquestion.judge';
    readonly roundId: RoundId;
    readonly questionNumber: number;
    readonly acceptedPlayers: readonly PlayerId[];
}
