// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { OpenQuestionAnswerCategory } from './OpenQuestionAnswerCategory';
import type { PlayerId } from './PlayerId';

export interface OpenQuestionGameMasterGroup {
    readonly text: string;
    readonly category: OpenQuestionAnswerCategory;
    readonly playerIds: readonly PlayerId[];
    readonly accepted: boolean | null;
}
