// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { OpenQuestionDisplayParticipant } from './OpenQuestionDisplayParticipant';
import type { OpenQuestionDisplayReveal } from './OpenQuestionDisplayReveal';
import type { OpenQuestionQuestionPhase } from './OpenQuestionQuestionPhase';

export interface OpenQuestionDisplayView {
    readonly type: 'openquestion';
    readonly questionNumber: number;
    readonly questionCount: number;
    readonly phase: OpenQuestionQuestionPhase;
    readonly text: string | null;
    readonly imageUrl: string | null;
    readonly answersCloseAt: number | null;
    readonly answeredCount: number;
    readonly participantCount: number;
    readonly participants: readonly OpenQuestionDisplayParticipant[];
    readonly reveal: OpenQuestionDisplayReveal | null;
}
