// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { OpenQuestionRevealedGroup } from './OpenQuestionRevealedGroup';

export interface OpenQuestionDisplayReveal {
    readonly expectedAnswer: string;
    readonly groups: readonly OpenQuestionRevealedGroup[];
    readonly withoutAnswer: readonly string[];
}
