// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

export type PackProblemCode = 'PackJsonInvalid' | 'PackPropertyMissing' | 'PackPropertyUnknown' | 'PackValueTypeInvalid' | 'PackValueOutOfRange' | 'PackTextLengthOutOfRange' | 'PackItemCountOutOfRange' | 'PackRoundTypeUnknown' | 'PackMediaPathInvalid' | 'PackMediaOutsidePack' | 'PackMediaTypeUnsupported' | 'PackMediaMissing' | 'PackMediaCaseMismatch' | 'PackMediaUnreadable' | 'PackAudioExcerptStartBeyondEnd' | 'PackLoadFailed' | 'QuizCorrectChoiceMissing' | 'QuizCorrectChoiceDuplicated' | 'QuizChoiceDuplicated' | 'BlindTestPointsMissing';
