// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { PackProblemCode } from './PackProblemCode';

export interface PackProblem {
    readonly code: PackProblemCode;
    readonly file: string;
    readonly path: string;
    readonly parameters: Readonly<Record<string, string>>;
}
