// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { GameId } from './GameId';
import type { Phase } from './Phase';
import type { PlayerId } from './PlayerId';
import type { PlayerRoundView } from './PlayerRoundView';
import type { PlayerStanding } from './PlayerStanding';
import type { RoundInfo } from './RoundInfo';

export interface PlayerSnapshot {
    readonly gameId: GameId;
    readonly version: number;
    readonly phase: Phase;
    readonly playerId: PlayerId;
    readonly nickname: string;
    readonly score: number;
    readonly playerCount: number;
    readonly round: RoundInfo | null;
    readonly roundView: PlayerRoundView | null;
    readonly standing: PlayerStanding | null;
    readonly finishedAt: number | null;
    readonly pausedAt: number | null;
}
