// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { BlindTestBuzz } from './BlindTestBuzz';
import type { BuzzerBuzz } from './BuzzerBuzz';
import type { QuizSubmitAnswer } from './QuizSubmitAnswer';

export type PlayerRoundIntent = BlindTestBuzz | BuzzerBuzz | QuizSubmitAnswer;
