// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { QuizChoiceLetter } from './QuizChoiceLetter';
import type { QuizQuestionPhase } from './QuizQuestionPhase';
import type { QuizVerdict } from './QuizVerdict';

export interface QuizPlayerView {
    readonly type: 'quiz';
    readonly questionNumber: number;
    readonly questionCount: number;
    readonly phase: QuizQuestionPhase;
    readonly choices: readonly QuizChoiceLetter[];
    readonly shownChoiceCount: number;
    readonly answersCloseAt: number | null;
    readonly participating: boolean;
    readonly answer: QuizChoiceLetter | null;
    readonly correctChoice: QuizChoiceLetter | null;
    readonly verdict: QuizVerdict | null;
    readonly points: number | null;
}
