// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { QuizChoiceView } from './QuizChoiceView';
import type { QuizDisplayReveal } from './QuizDisplayReveal';
import type { QuizQuestionPhase } from './QuizQuestionPhase';

export interface QuizDisplayView {
    readonly type: 'quiz';
    readonly questionNumber: number;
    readonly questionCount: number;
    readonly phase: QuizQuestionPhase;
    readonly text: string;
    readonly imageUrl: string | null;
    readonly choices: readonly QuizChoiceView[];
    readonly answersCloseAt: number | null;
    readonly answeredCount: number;
    readonly participantCount: number;
    readonly reveal: QuizDisplayReveal | null;
}
