// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { QuizGameMasterAnswer } from './QuizGameMasterAnswer';
import type { QuizGameMasterChoice } from './QuizGameMasterChoice';
import type { QuizQuestionPhase } from './QuizQuestionPhase';

export interface QuizGameMasterView {
    readonly type: 'quiz';
    readonly questionNumber: number;
    readonly questionCount: number;
    readonly phase: QuizQuestionPhase;
    readonly text: string;
    readonly questionShown: boolean;
    readonly choices: readonly QuizGameMasterChoice[];
    readonly answersCloseAt: number | null;
    readonly answers: readonly QuizGameMasterAnswer[];
}
