// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { PlayerId } from './PlayerId';
import type { QuizChoiceLetter } from './QuizChoiceLetter';

export interface QuizGameMasterAnswer {
    readonly playerId: PlayerId;
    readonly nickname: string;
    readonly choice: QuizChoiceLetter | null;
}
