// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { QuizChoiceLetter } from './QuizChoiceLetter';
import type { RoundId } from './RoundId';

export interface QuizSubmitAnswer {
    readonly type: 'quiz.submitAnswer';
    readonly roundId: RoundId;
    readonly questionNumber: number;
    readonly choice: QuizChoiceLetter;
}
