// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { QuizChoiceLetter } from './QuizChoiceLetter';
import type { QuizRevealedAnswer } from './QuizRevealedAnswer';

export interface QuizDisplayReveal {
    readonly correctChoice: QuizChoiceLetter;
    readonly answers: readonly QuizRevealedAnswer[];
}
