// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { PlayerId } from './PlayerId';

export interface RankedPlayer {
    readonly id: PlayerId;
    readonly nickname: string;
    readonly isConnected: boolean;
    readonly rank: number;
    readonly isTied: boolean;
    readonly score: number;
}
