// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { RecoverSessionRefusal } from './RecoverSessionRefusal';

export interface RecoverSessionResult {
    readonly refusal: RecoverSessionRefusal | null;
    readonly token: string | null;
    readonly lastClientSeq: number;
}
