// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

import type { GameId } from './GameId';
import type { ScheduledRound } from './ScheduledRound';

export interface ReorderRoundsRequest {
    readonly gameId: GameId;
    readonly expectedOrder: readonly ScheduledRound[];
    readonly newOrder: readonly ScheduledRound[];
}
