// <auto-generated>
// Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
// change the C# types, then run `npm run generate:contracts` from client/.
// </auto-generated>

export interface ShowPreviewStepRequest {
    readonly roundNumber: number;
    readonly stepNumber: number;
    readonly playExcerpt: boolean;
}
