using System.Reflection;
using System.Reflection.Emit;

namespace PartyGame.Engine.Tests;

/// <summary>
/// Lists the methods and constructors called by the code of an assembly, by reading the IL of every method body,
/// including those generated by the compiler for lambdas, iterators and records.
/// </summary>
internal static class MethodCalls
{
    private const BindingFlags Declared =
        BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

    private static readonly Dictionary<short, OpCode> _opCodes = typeof(OpCodes)
        .GetFields(BindingFlags.Public | BindingFlags.Static)
        .Select(f => (OpCode)f.GetValue(null)!)
        .ToDictionary(o => o.Value);

    public static IEnumerable<(MethodBase Caller, MethodBase Callee)> In(Assembly assembly) =>
        assembly.GetTypes().SelectMany(InType);

    public static IEnumerable<(MethodBase Caller, MethodBase Callee)> InType(Type type) =>
        type.GetMethods(Declared).Cast<MethodBase>()
            .Concat(type.GetConstructors(Declared))
            .SelectMany(method => CalledBy(method).Select(callee => (method, callee)));

    private static IEnumerable<MethodBase> CalledBy(MethodBase method)
    {
        var il = method.GetMethodBody()?.GetILAsByteArray();
        if (il is null)
        {
            yield break;
        }

        var typeArguments = method.DeclaringType is { IsGenericType: true } type ? type.GetGenericArguments() : null;
        var methodArguments = method is MethodInfo { IsGenericMethod: true } ? method.GetGenericArguments() : null;

        var position = 0;
        while (position < il.Length)
        {
            short value = il[position++];
            if (value == 0xFE)
            {
                value = unchecked((short)(0xFE00 | il[position++]));
            }

            var opCode = _opCodes[value];
            if (opCode.OperandType == OperandType.InlineMethod)
            {
                var token = BitConverter.ToInt32(il, position);
                yield return method.Module.ResolveMethod(token, typeArguments, methodArguments)!;
            }

            position += OperandSize(opCode.OperandType, il, position);
        }
    }

    private static int OperandSize(OperandType operandType, byte[] il, int position) => operandType switch
    {
        OperandType.InlineNone => 0,
        OperandType.ShortInlineBrTarget or OperandType.ShortInlineI or OperandType.ShortInlineVar => 1,
        OperandType.InlineVar => 2,
        OperandType.InlineI8 or OperandType.InlineR => 8,
        OperandType.InlineSwitch => 4 + (4 * BitConverter.ToInt32(il, position)),
        _ => 4,
    };
}
