using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using PartyGame.TypeGen.Model;

namespace PartyGame.TypeGen;

/// <summary>
/// Writes declarations as TypeScript files: one file per declaration, plus an <c>index.ts</c> that re-exports them all.
/// The output is final, so it is excluded from ESLint and Prettier.
/// </summary>
internal static partial class TypeScriptWriter
{
    public const string IndexFile = "index.ts";

    // Line endings are fixed explicitly: generated files are compared byte for byte, whatever the checkout of this file.
    public static readonly string Header =
        """
        // <auto-generated>
        // Generated by tools/PartyGame.TypeGen from PartyGame.Contracts. Do not edit by hand:
        // change the C# types, then run `npm run generate:contracts` from client/.
        // </auto-generated>
        """.ReplaceLineEndings("\n") + "\n\n";

    private const string Indent = "    ";

    public static ImmutableArray<GeneratedFile> Write(IEnumerable<TsDeclaration> declarations)
    {
        var sorted = declarations.OrderBy(d => d.Name, StringComparer.Ordinal).ToList();

        var files = sorted.Select(d => new GeneratedFile(FileName(d.Name), Header + WriteDeclaration(d))).ToList();
        files.Add(new GeneratedFile(IndexFile, Header + WriteIndex(sorted)));
        return [.. files];
    }

    private static string FileName(string declarationName) => $"{declarationName}.ts";

    private static string WriteIndex(List<TsDeclaration> declarations)
    {
        if (declarations.Count == 0)
        {
            return "export {};\n";
        }

        var builder = new StringBuilder();
        foreach (var declaration in declarations)
        {
            builder.Append(CultureInfo.InvariantCulture, $"export type * from './{declaration.Name}';\n");
        }

        return builder.ToString();
    }

    private static string WriteDeclaration(TsDeclaration declaration)
    {
        var builder = new StringBuilder();

        var imports = References(declaration).Where(name => name != declaration.Name).Distinct().Order(StringComparer.Ordinal).ToList();
        foreach (var name in imports)
        {
            builder.Append(CultureInfo.InvariantCulture, $"import type {{ {name} }} from './{name}';\n");
        }

        if (imports.Count > 0)
        {
            builder.Append('\n');
        }

        switch (declaration)
        {
            case TsInterface tsInterface:
                builder.Append(CultureInfo.InvariantCulture, $"export interface {tsInterface.Name} {{");
                if (tsInterface.Properties.IsEmpty)
                {
                    builder.Append("}\n");
                    break;
                }

                builder.Append('\n');
                foreach (var property in tsInterface.Properties)
                {
                    builder.Append(CultureInfo.InvariantCulture, $"{Indent}readonly {PropertyName(property.Name)}: {TypeExpression(property.Type)};\n");
                }

                builder.Append("}\n");
                break;

            case TsStringUnion union:
                builder.Append(CultureInfo.InvariantCulture, $"export type {union.Name} = {string.Join(" | ", union.Values.Select(StringLiteral))};\n");
                break;

            case TsBrandedString branded:
                builder.Append(CultureInfo.InvariantCulture, $"export type {branded.Name} = string & {{ readonly __brand: {StringLiteral(branded.Name)} }};\n");
                break;

            case TsUnion union:
                builder.Append(CultureInfo.InvariantCulture, $"export type {union.Name} = {string.Join(" | ", union.Members)};\n");
                break;

            default:
                throw new InvalidOperationException($"Unexpected declaration {declaration.GetType().Name}.");
        }

        return builder.ToString();
    }

    private static IEnumerable<string> References(TsDeclaration declaration) => declaration switch
    {
        TsInterface tsInterface => tsInterface.Properties.SelectMany(p => References(p.Type)),
        TsUnion union => union.Members,
        _ => [],
    };

    private static IEnumerable<string> References(TsType type) => type switch
    {
        TsReferenceType reference => [reference.Name],
        TsNullableType nullable => References(nullable.Inner),
        TsArrayType array => References(array.Element),
        TsRecordType record => References(record.Value),
        _ => [],
    };

    private static string TypeExpression(TsType type) => type switch
    {
        TsPrimitiveType primitive => primitive.Name,
        TsReferenceType reference => reference.Name,
        TsNullableType nullable => $"{TypeExpression(nullable.Inner)} | null",
        TsArrayType { Element: TsNullableType or TsArrayType } array => $"readonly ({TypeExpression(array.Element)})[]",
        TsArrayType array => $"readonly {TypeExpression(array.Element)}[]",
        TsRecordType record => $"Readonly<Record<string, {TypeExpression(record.Value)}>>",
        TsLiteralType { Value: string text } => StringLiteral(text),
        TsLiteralType literal => Convert.ToString(literal.Value, CultureInfo.InvariantCulture)!,
        _ => throw new InvalidOperationException($"Unexpected type {type.GetType().Name}."),
    };

    private static string PropertyName(string name) => IdentifierPattern().IsMatch(name) ? name : StringLiteral(name);

    private static string StringLiteral(string text) => $"'{text.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("'", "\\'", StringComparison.Ordinal)}'";

    [GeneratedRegex("^[A-Za-z_$][A-Za-z0-9_$]*$")]
    private static partial Regex IdentifierPattern();
}
