using System.Collections.Immutable;
using PartyGame.Contracts;

namespace PartyGame.Engine;

/// <summary>
/// Complete state of a game. Immutable: the engine derives a new state with <c>with</c> and never modifies the one it receives.
/// It is serializable as is, to persist the game after each transition.
/// </summary>
/// <param name="GameId">Identifier of the game.</param>
/// <param name="Version">
/// Number of the state, carried by every snapshot. The game loop increments it with each transition that changes the
/// state, never the engine: it is persisted with the state, so that a game resumed after a crash goes on counting.
/// </param>
/// <param name="Phase">Current phase of the game.</param>
/// <param name="JoinAddress">
/// The IPv4 address phones join at, shown on the TV screen, or <see langword="null"/> when the server knows none. Part of
/// the state so that a change of address is broadcast like any other change.
/// </param>
/// <param name="Players">Registered players, in order of arrival.</param>
/// <param name="PlayerTokens">The player each token identifies. Secret: no projection ever contains it.</param>
public sealed record GameState(
    GameId GameId,
    long Version,
    GamePhase Phase,
    string? JoinAddress,
    ImmutableArray<Player> Players,
    ImmutableDictionary<PlayerToken, PlayerId> PlayerTokens)
{
    /// <summary>
    /// Creates the state of a new game: a lobby without any player, at version 1.
    /// </summary>
    /// <param name="gameId">Identifier of the game, generated by the caller since the engine has no randomness of its own.</param>
    /// <param name="joinAddress">The address phones join at, chosen by the server at startup, if any.</param>
    public static GameState Create(GameId gameId, string? joinAddress) =>
        new(gameId, Version: 1, GamePhase.Lobby, joinAddress, [], ImmutableDictionary<PlayerToken, PlayerId>.Empty);
}
