using System.Collections.Immutable;
using PartyGame.Contracts;

namespace PartyGame.Engine;

/// <summary>
/// Complete state of a game. Immutable: the engine derives a new state with <c>with</c> and never modifies the one it receives.
/// It is serializable as is, to persist the game after each transition.
/// </summary>
/// <param name="GameId">Identifier of the game.</param>
/// <param name="Phase">Current phase of the game.</param>
/// <param name="Players">Registered players, in order of arrival.</param>
/// <param name="PlayerTokens">The player each token identifies. Secret: no projection ever contains it.</param>
public sealed record GameState(
    GameId GameId,
    GamePhase Phase,
    ImmutableArray<Player> Players,
    ImmutableDictionary<PlayerToken, PlayerId> PlayerTokens)
{
    /// <summary>
    /// Creates the state of a new game: a lobby without any player.
    /// </summary>
    /// <param name="gameId">Identifier of the game, generated by the caller since the engine has no randomness of its own.</param>
    public static GameState Create(GameId gameId) =>
        new(gameId, GamePhase.Lobby, [], ImmutableDictionary<PlayerToken, PlayerId>.Empty);
}
