using System.Text.Json.Serialization;
using PartyGame.Contracts.Serialization;

namespace PartyGame.Engine;

/// <summary>
/// Secret that a phone presents to be recognized as the same player after a reconnection.
/// It is sent once, in the answer to the registration, and never appears in a snapshot.
/// </summary>
/// <param name="Value">The token, generated by the server.</param>
[JsonConverter(typeof(TypedIdJsonConverterFactory))]
public readonly record struct PlayerToken(string Value);
